export const ActionTypes = {
LOGIN_REQUEST: 'LOGIN_REQUEST',
SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
TEST_ACTION:'TEST_ACTION',
APP_LOADER: 'APP_LOADER',
PROFILE_UPDATE_REQUEST:'PROFILE_UPDATE_REQUEST',
GET_PROFILE_DATA: 'GET_PROFILE_DATA',
ADD_CALORIES: 'ADD_CALORIES',
UPDATED_CALORIES: 'UPDATED_CALORIES',
};
